### ISSUE TITLE
RPC: Incorrect block number parsing

### ISSUE THREAD

**Issue by kamilgg** [oort-tech/Olympus#45]
**Describe the bug**
We tried to make our own indexer based on The Graph. And when The Graph node tries to get a block by calling eth_getBlockByNumber it gets an error. 
The thing is that in RPC this method doesn't accept an integer type number, but only a string (not 2, but "2").

The Graph is failing with
`graph-node_1  | Dec 02 14:44:15.077 WARN Trying again after eth_getBlockByNumber(0, false) RPC call failed (attempt #13) with result Err(Decoder error: Error("missing field `stateRoot`", line: 0, column: 0)), provider: mainnet-rpc-0`

**To Reproduce**
Here are manual tests:
1. `➜  oort-index curl https://beta-rpc.mainnet.computecoin.com/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":[0,false],"id":1,"jsonrpc":"2.0"}'
➜  oort-index `
2. `➜  oort-index curl https://beta-rpc.mainnet.computecoin.com/ \
  -X POST \
  -H "Content-Type: application/json" \
  --data '{"method":"eth_getBlockByNumber","params":["0",false],"id":1,"jsonrpc":"2.0"}'
➜ {"id":1,"jsonrpc":"2.0","result":{"number":"0x0","nonce":null,"difficulty":"0x0","extraData":"0x00","hash":"0x314a53d362f3918c463488b47561d55d4aa720f40c5f1a1bbc441b1a6b95a390","parentHash":"0x0000000000000000000000000000000000000000000000000000000000000000","gasUsed":"0x0","minGasPrice":"0x0","gasLimit":"0x7a1200","timestamp":"0x5a497a00","transactions":[],"miner":"0x1144b522f45265c2dfdbaee8e324719e63a1694c"}}%`

**Additional context**
So apparently the problem is here:
https://github.com/oort-tech/Olympus/blob/5e3c32f0aaf3e9d613fc116bf96c55990287cbbd/mcp/rpc/rpc.cpp#L1407
I think it should accept both integer and string types.

**Comment by molecula451** [comment]
fixed on master branch this can be closed
