### ISSUE TITLE
Deployment Failed: Deploy contract report 'Insufficient balance'

### ISSUE THREAD

**Issue by catlina-nero** [oort-tech/Olympus#46]
When I use truffle to deploy contract, I confirm my account has balance, but I get this error:

Error:  *** Deployment Failed ***
"Migrations" -- Insufficient balance -- Reason given: Custom error (could not decode)..

Looks like an error that truffle cannot decode is returned.

**Comment by MrAA007** [comment]
use "@truffle/hdwallet-provider": "^2.1.5" replace "truffle-hdwallet-provider": "^1.0.4". truffle-hdwallet-provider sinature do not include chainId(eip155).
olympus fix crash and do not support non-replay protected transactions. [](https://github.com/oort-tech/Olympus/commit/59434a07b695676d35151f068ffa07478241f238)

**Comment by MrAA007** [comment]
[https://github.com/oort-tech/Olympus/commit/59434a07b695676d35151f068ffa07478241f238](url)
